name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"
      - run: pwsh ./test.ps1 -UseDocker
