name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"
      - run: pwsh ./test.ps1 -UseDocker
