name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"
      - run: pwsh ./test.ps1 -UseDocker
